/**
 * app.js
 * ─────────────────────────────────────────────────────────────────
 * Wires the UI to:
 *   1. Open-Meteo Geocoding API   — free, keyless, city → lat/lon
 *   2. Open-Meteo Air Quality API — free, keyless, live AQI/pollutants
 *   3. promptEngine.js            — builds the structured prompt
 *   4. graniteConnector.js        — optional real Granite call
 * No API keys or signup required for the default working demo.
 * ─────────────────────────────────────────────────────────────────
 */

const GEOCODE_URL = "https://geocoding-api.open-meteo.com/v1/search";
const AQI_URL = "https://air-quality-api.open-meteo.com/v1/air-quality";

let selectedCity = null; // { name, country, lat, lon }

const citySearch = document.getElementById("citySearch");
const citySuggestions = document.getElementById("citySuggestions");
const askBtn = document.getElementById("askBtn");
const askBtnText = document.getElementById("askBtnText");
const errorMsg = document.getElementById("errorMsg");

const dataPanel = document.getElementById("dataPanel");
const dataGrid = document.getElementById("dataGrid");
const sourceNote = document.getElementById("sourceNote");

const responsePanel = document.getElementById("responsePanel");
const responseContent = document.getElementById("responseContent");
const engineTag = document.getElementById("engineTag");

const promptPanel = document.getElementById("promptPanel");
const promptDump = document.getElementById("promptDump");

// ───────────── City autocomplete (debounced) ─────────────
let debounceTimer;
citySearch.addEventListener("input", () => {
  clearTimeout(debounceTimer);
  selectedCity = null;
  const query = citySearch.value.trim();
  if (query.length < 2) {
    citySuggestions.classList.add("hidden");
    return;
  }
  debounceTimer = setTimeout(() => fetchCitySuggestions(query), 300);
});

document.addEventListener("click", (e) => {
  if (!citySuggestions.contains(e.target) && e.target !== citySearch) {
    citySuggestions.classList.add("hidden");
  }
});

async function fetchCitySuggestions(query) {
  try {
    const res = await fetch(`${GEOCODE_URL}?name=${encodeURIComponent(query)}&count=6&language=en&format=json`);
    const data = await res.json();
    renderSuggestions(data.results || []);
  } catch (err) {
    console.error("Geocoding error:", err);
  }
}

function renderSuggestions(results) {
  if (!results.length) {
    citySuggestions.classList.add("hidden");
    return;
  }
  citySuggestions.innerHTML = "";
  results.forEach((r) => {
    const div = document.createElement("div");
    const region = r.admin1 ? `${r.admin1}, ` : "";
    div.textContent = `${r.name}, ${region}${r.country}`;
    div.addEventListener("click", () => {
      selectedCity = { name: r.name, country: r.country, lat: r.latitude, lon: r.longitude };
      citySearch.value = div.textContent;
      citySuggestions.classList.add("hidden");
    });
    citySuggestions.appendChild(div);
  });
  citySuggestions.classList.remove("hidden");
}

// ───────────── Main "Ask AirSense" flow ─────────────
askBtn.addEventListener("click", handleAsk);

async function handleAsk() {
  errorMsg.classList.add("hidden");

  if (!selectedCity) {
    showError("Please search for and select a city from the suggestions list.");
    return;
  }

  setLoading(true);
  try {
    const aqiData = await fetchAirQuality(selectedCity.lat, selectedCity.lon);
    renderDataPanel(selectedCity, aqiData);

    const profile = {
      ageGroup: document.getElementById("ageGroup").value,
      healthCondition: document.getElementById("healthCondition").value,
      activity: document.getElementById("activity").value,
    };

    const cityLabel = `${selectedCity.name}, ${selectedCity.country}`;
    const prompt = buildStructuredPrompt(cityLabel, aqiData, profile);
    promptDump.textContent = prompt;
    promptPanel.classList.remove("hidden");

    const useGranite = document.getElementById("useGranite").checked;
    const apiKey = document.getElementById("wxApiKey").value.trim();
    const projectId = document.getElementById("wxProjectId").value.trim();

    if (useGranite && apiKey && projectId) {
      try {
        engineTag.textContent = "(generated by live IBM Granite model)";
        const raw = await callGraniteModel(prompt, apiKey, projectId);
        renderRawResponse(raw);
      } catch (graniteErr) {
        console.warn("Granite call failed, falling back to local engine:", graniteErr);
        engineTag.textContent = "(local reasoning engine — Granite call failed, see console)";
        renderStructuredResponse(localReasoningEngine(cityLabel, aqiData, profile));
      }
    } else {
      engineTag.textContent = "(local rule-based reasoning engine)";
      renderStructuredResponse(localReasoningEngine(cityLabel, aqiData, profile));
    }

    responsePanel.classList.remove("hidden");
    responsePanel.scrollIntoView({ behavior: "smooth", block: "start" });
  } catch (err) {
    console.error(err);
    showError("Could not fetch live air quality data. Please try again in a moment.");
  } finally {
    setLoading(false);
  }
}

async function fetchAirQuality(lat, lon) {
  const params = new URLSearchParams({
    latitude: lat,
    longitude: lon,
    current: "us_aqi,pm2_5,pm10,ozone,nitrogen_dioxide",
    timezone: "auto",
  });
  const res = await fetch(`${AQI_URL}?${params.toString()}`);
  if (!res.ok) throw new Error("Air quality API request failed");
  const data = await res.json();
  return {
    us_aqi: data.current.us_aqi,
    pm2_5: data.current.pm2_5,
    pm10: data.current.pm10,
    ozone: data.current.ozone,
    nitrogen_dioxide: data.current.nitrogen_dioxide,
    time: data.current.time,
  };
}

function renderDataPanel(city, aqi) {
  const band = categorizeAqi(aqi.us_aqi);
  dataGrid.innerHTML = `
    <div class="data-card"><div class="val ${band.cssClass}">${aqi.us_aqi}</div><div class="label">US AQI — ${band.category}</div></div>
    <div class="data-card"><div class="val">${aqi.pm2_5}</div><div class="label">PM2.5 (µg/m³)</div></div>
    <div class="data-card"><div class="val">${aqi.pm10}</div><div class="label">PM10 (µg/m³)</div></div>
    <div class="data-card"><div class="val">${aqi.ozone}</div><div class="label">Ozone (µg/m³)</div></div>
    <div class="data-card"><div class="val">${aqi.nitrogen_dioxide}</div><div class="label">NO₂ (µg/m³)</div></div>
  `;
  sourceNote.textContent = `Source: Open-Meteo Air Quality API · ${city.name}, ${city.country} · Retrieved at ${aqi.time}`;
  dataPanel.classList.remove("hidden");
}

function renderStructuredResponse({ headline, riskLine, band, tips }) {
  responseContent.innerHTML = `
    <div class="headline ${band.cssClass}">${headline}</div>
    <div class="risk-line">${riskLine}</div>
    <strong>Recommended actions for you:</strong>
    <ol>${tips.map((t) => `<li>${t}</li>`).join("")}</ol>
  `;
}

function renderRawResponse(text) {
  responseContent.innerHTML = `<div class="risk-line">${text.replace(/\n/g, "<br/>")}</div>`;
}

function setLoading(isLoading) {
  askBtn.disabled = isLoading;
  askBtnText.textContent = isLoading ? "Fetching live data..." : "Ask AirSense";
}

function showError(msg) {
  errorMsg.textContent = msg;
  errorMsg.classList.remove("hidden");
}
